svn rename CrewArmLowerL01n.png CrewArmLowerLSuit01n.png
svn rename CrewArmLowerL01n.png.meta CrewArmLowerLSuit01n.png.meta
svn rename CrewArmLowerR01.png CrewArmLowerRSuit01.png
svn rename CrewArmLowerR01.png.meta CrewArmLowerRSuit01.png.meta
svn rename CrewArmLowerR01n.png CrewArmLowerRSuit01n.png
svn rename CrewArmLowerR01n.png.meta CrewArmLowerRSuit01n.png.meta
svn rename CrewArmUpperL01.png CrewArmUpperLSuit01.png
svn rename CrewArmUpperL01.png.meta CrewArmUpperLSuit01.png.meta
svn rename CrewArmUpperL01n.png CrewArmUpperLSuit01n.png
svn rename CrewArmUpperL01n.png.meta CrewArmUpperLSuit01n.png.meta
svn rename CrewArmUpperR01.png CrewArmUpperRSuit01.png
svn rename CrewArmUpperR01.png.meta CrewArmUpperRSuit01.png.meta
svn rename CrewArmUpperR01n.png CrewArmUpperRSuit01n.png
svn rename CrewArmUpperR01n.png.meta CrewArmUpperRSuit01n.png.meta
svn rename CrewFootL01.png CrewFootLSuit01.png
svn rename CrewFootL01.png.meta CrewFootLSuit01.png.meta
svn rename CrewFootL01n.png CrewFootLSuit01n.png
svn rename CrewFootL01n.png.meta CrewFootLSuit01n.png.meta
svn rename CrewFootR01.png CrewFootRSuit01.png
svn rename CrewFootR01.png.meta CrewFootRSuit01.png.meta
svn rename CrewFootR01n.png CrewFootRSuit01n.png
svn rename CrewFootR01n.png.meta CrewFootRSuit01n.png.meta
svn rename CrewLegLowerL01.png CrewLegLowerLSuit01.png
svn rename CrewLegLowerL01.png.meta CrewLegLowerLSuit01.png.meta
svn rename CrewLegLowerL01n.png CrewLegLowerLSuit01n.png
svn rename CrewLegLowerL01n.png.meta CrewLegLowerLSuit01n.png.meta
svn rename CrewLegLowerR01.png CrewLegLowerRSuit01.png
svn rename CrewLegLowerR01.png.meta CrewLegLowerRSuit01.png.meta
svn rename CrewLegLowerR01n.png CrewLegLowerRSuit01n.png
svn rename CrewLegLowerR01n.png.meta CrewLegLowerRSuit01n.png.meta
svn rename CrewLegUpperL01.png CrewLegUpperLSuit01.png
svn rename CrewLegUpperL01.png.meta CrewLegUpperLSuit01.png.meta
svn rename CrewLegUpperL01n.png CrewLegUpperLSuit01n.png
svn rename CrewLegUpperL01n.png.meta CrewLegUpperLSuit01n.png.meta
svn rename CrewLegUpperR01.png CrewLegUpperRSuit01.png
svn rename CrewLegUpperR01.png.meta CrewLegUpperRSuit01.png.meta
svn rename CrewLegUpperR01n.png CrewLegUpperRSuit01n.png
svn rename CrewLegUpperR01n.png.meta CrewLegUpperRSuit01n.png.meta
svn rename CrewShoulderL01.png CrewShoulderLSuit01.png
svn rename CrewShoulderL01.png.meta CrewShoulderLSuit01.png.meta
svn rename CrewShoulderL01n.png CrewShoulderLSuit01n.png
svn rename CrewShoulderL01n.png.meta CrewShoulderLSuit01n.png.meta
svn rename CrewShoulderR01.png CrewShoulderRSuit01.png
svn rename CrewShoulderR01.png.meta CrewShoulderRSuit01.png.meta
svn rename CrewShoulderR01n.png CrewShoulderRSuit01n.png
svn rename CrewShoulderR01n.png.meta CrewShoulderRSuit01n.png.meta
svn rename CrewTorso01.png CrewTorsoSuit01.png
svn rename CrewTorso01.png.meta CrewTorsoSuit01.png.meta
svn rename CrewTorso01n.png CrewTorsoSuit01n.png
svn rename CrewTorso01n.png.meta CrewTorsoSuit01n.png.meta